version: '2'

services:
  php-nginx:
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    networks:
      - default
      - nginx-proxy
  mysql:
    networks:
      - default
      - phpmyadmin

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  phpmyadmin:
    external:
      name: phpmyadmin
